### ISSUE TITLE
NuGet-publish action

### ISSUE THREAD

**Issue by Smaug123** [G-Research/common-actions#3]
Consider forking https://github.com/Smaug123/publish-nuget-action , which performs a `dotnet nuget push` and a GitHub artefact attestation on the resulting NuGet.org package.

A minimal usage of this action, to help you decide whether this is an action you're interested in taking:

```yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: ''
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack
    - name: Publish NuGet package
      uses: Smaug123/publish-nuget-action@0cde38eae4a32ebe5f3c882e7027ac57ef513a7f
      with:
        package-name: WoofWare.Test.Thing
        nuget-key: ${{ secrets.NUGET_API_KEY }}
        nupkg-dir: bin/Release/
```
